#!/bin/bash
# detect_machine.sh [ROOT_DIR]
#
# Probes the NUMA layout and writes ROOT_DIR/machine.env with:
#   - the CPU-bearing physical nodes,
#   - a maximal-spread logical->physical order (NUMA_NODE_ORDER), and
#   - a numactl binding string + thread count.
#
# Run this once per machine. The run scripts can `source machine.env`, and
# numaLib/numa_nodemap.hpp reads NUMA_NODE_ORDER at runtime. You may hand-edit
# machine.env afterward (e.g. to pick a different node order).
set -u
ROOT="${1:-$(cd "$(dirname "$0")" && pwd)}"
OUT="$ROOT/machine.env"

# --- CPU-bearing physical nodes (ascending, numeric) ---
mapfile -t cpu_nodes < <(
    for nd in /sys/devices/system/node/node[0-9]*; do
        [ -e "$nd" ] || continue
        cl=$(cat "$nd/cpulist" 2>/dev/null)
        [ -n "$cl" ] && echo "${nd##*/node}"
    done | sort -n
)
[ ${#cpu_nodes[@]} -eq 0 ] && cpu_nodes=(0)

# --- outside-in spread order: [a,b,...,y,z] -> [a,z,b,y,...] (farthest-apart first) ---
spread=()
lo=0; hi=$(( ${#cpu_nodes[@]} - 1 ))
while [ "$lo" -le "$hi" ]; do
    spread+=("${cpu_nodes[$lo]}"); lo=$((lo+1))
    if [ "$lo" -le "$hi" ]; then spread+=("${cpu_nodes[$hi]}"); hi=$((hi-1)); fi
done

num_phys=$(ls -d /sys/devices/system/node/node[0-9]* 2>/dev/null | wc -l)
num_cpu=${#cpu_nodes[@]}
cpu_csv=$(IFS=,; echo "${cpu_nodes[*]}")
spread_csv=$(IFS=,; echo "${spread[*]}")
total_threads=$(nproc)

cat > "$OUT" <<EOF
# machine.env -- auto-generated by detect_machine.sh on $(date) ($(hostname))
# Sourced by run scripts; NUMA_NODE_ORDER is also read by numaLib/numa_nodemap.hpp.
# Re-run detect_machine.sh on a new machine, or hand-edit the values below.

export NUM_PHYS_NODES=$num_phys          # total NUMA nodes (including memory-only)
export CPU_NODES=$cpu_csv                 # physical nodes that have CPUs (ascending)
export NUM_CPU_NODES=$num_cpu
export TOTAL_THREADS=$total_threads

# Logical -> physical order used by numa<T,k> / thread_numa<k>:
#   logical k maps to entry (k % NUM_CPU_NODES) of this list.
# Default is "outside-in" (farthest-apart first) for worst-case NUMA locality.
# Hand-edit this line to choose a different order for this machine.
export NUMA_NODE_ORDER=$spread_csv

# numactl binding for the benchmarks (bind to the CPU-bearing nodes).
export NUMACTL_BIND="--cpunodebind=$cpu_csv --membind=$cpu_csv"
EOF

echo "Wrote $OUT"
echo "  physical nodes        : $num_phys"
echo "  CPU nodes (ascending) : $cpu_csv"
echo "  NUMA_NODE_ORDER       : $spread_csv   (logical k -> this[k % $num_cpu])"
echo "  total threads         : $total_threads"
