#!/bin/bash
# detect_machine.sh [ROOT_DIR]
#
# Probes the NUMA layout and writes ROOT_DIR/machine.env with:
#   - the CPU-bearing physical nodes,
#   - the physical nodes the experiment actually runs on (NUMA_NODE_ORDER), and
#   - a numactl binding string + thread count.
#
# The benchmarks use a fixed number of logical partitions (numa<T,k> and
# thread_numa<k> are instantiated at k=0 and k=MAX_NODE, and the UMF allocator
# builds NUMA_NODE_NUM pools) -- 2 by default.  So we do NOT bind to every CPU
# node on the machine; we pick the NUM_PARTITIONS farthest-apart nodes and bind
# to exactly those, which is what makes the worst-case-locality comparison mean
# the same thing on a 2-node box and on an 8-node box.
#
#   stormbreaker (CPU nodes 0,1)      -> NUMA_NODE_ORDER=0,1   bind 0,1
#   Perlmutter   (CPU nodes 0..7)     -> NUMA_NODE_ORDER=0,7   bind 0,7
#
# Override the partition count with NUM_PARTITIONS=4 bash detect_machine.sh
#
# Run this once per machine. The run scripts source machine.env, and
# numaLib/numa_nodemap.hpp reads NUMA_NODE_ORDER at runtime. You may hand-edit
# machine.env afterward (e.g. to pick a different node pair).
set -u
ROOT="${1:-$(cd "$(dirname "$0")" && pwd)}"
OUT="$ROOT/machine.env"

# --- CPU-bearing physical nodes (ascending, numeric) ---
mapfile -t cpu_nodes < <(
    for nd in /sys/devices/system/node/node[0-9]*; do
        [ -e "$nd" ] || continue
        cl=$(cat "$nd/cpulist" 2>/dev/null)
        [ -n "$cl" ] && echo "${nd##*/node}"
    done | sort -n
)
[ ${#cpu_nodes[@]} -eq 0 ] && cpu_nodes=(0)

# --- outside-in spread order: [a,b,...,y,z] -> [a,z,b,y,...] (farthest-apart first) ---
spread=()
lo=0; hi=$(( ${#cpu_nodes[@]} - 1 ))
while [ "$lo" -le "$hi" ]; do
    spread+=("${cpu_nodes[$lo]}"); lo=$((lo+1))
    if [ "$lo" -le "$hi" ]; then spread+=("${cpu_nodes[$hi]}"); hi=$((hi-1)); fi
done

num_phys=$(ls -d /sys/devices/system/node/node[0-9]* 2>/dev/null | wc -l)
num_cpu=${#cpu_nodes[@]}

# --- the nodes this experiment runs on: the first NUM_PARTITIONS of the spread ---
NUM_PARTITIONS="${NUM_PARTITIONS:-2}"
[ "$NUM_PARTITIONS" -gt "$num_cpu" ] && NUM_PARTITIONS=$num_cpu
[ "$NUM_PARTITIONS" -lt 1 ] && NUM_PARTITIONS=1
part=("${spread[@]:0:$NUM_PARTITIONS}")

# logical -> physical order (order matters: logical k maps to entry k)
part_csv=$(IFS=,; echo "${part[*]}")
# numactl binding over the same set, ascending (numactl ignores order)
mapfile -t part_sorted < <(printf '%s\n' "${part[@]}" | sort -n)
bind_csv=$(IFS=,; echo "${part_sorted[*]}")

cpu_csv=$(IFS=,; echo "${cpu_nodes[*]}")
spread_csv=$(IFS=,; echo "${spread[*]}")
total_threads=$(nproc)

# --- hardware threads on the partition nodes only ---
# The benchmarks split threads evenly across the two partitions
# (ycsb/src/main.cpp:180 and DataStructureTests do num_threads / 2, integer
# division), so this must be EVEN.  On a machine where the partitions are a
# subset of the node set this is much smaller than TOTAL_THREADS -- which is the
# whole point: binding to 2 of 8 nodes gives you 2 nodes' worth of CPUs.
count_cpus() {  # "0-19,40-59" -> 40
    local list="$1" n=0 part lo hi
    [ -z "$list" ] && { echo 0; return; }
    IFS=',' read -ra parts <<< "$list"
    for part in "${parts[@]}"; do
        if [[ "$part" == *-* ]]; then
            lo=${part%%-*}; hi=${part##*-}; n=$(( n + hi - lo + 1 ))
        else
            n=$(( n + 1 ))
        fi
    done
    echo "$n"
}
part_threads=0
for nd in "${part[@]}"; do
    cl=$(cat "/sys/devices/system/node/node$nd/cpulist" 2>/dev/null)
    part_threads=$(( part_threads + $(count_cpus "$cl") ))
done
# force even: the benchmarks halve it
part_threads=$(( part_threads - part_threads % 2 ))
[ "$part_threads" -lt 2 ] && part_threads=2

cat > "$OUT" <<EOF
# machine.env -- auto-generated by detect_machine.sh on $(date) ($(hostname))
# Sourced by run scripts; NUMA_NODE_ORDER is also read by numaLib/numa_nodemap.hpp.
# Re-run detect_machine.sh on a new machine, or hand-edit the values below.

export NUM_PHYS_NODES=$num_phys          # total NUMA nodes (including memory-only)
export CPU_NODES=$cpu_csv                 # physical nodes that have CPUs (ascending)
export NUM_CPU_NODES=$num_cpu
export TOTAL_THREADS=$total_threads

# All CPU nodes ordered outside-in (farthest-apart first), for reference:
#   $spread_csv

# Logical -> physical order used by numa<T,k> / thread_numa<k>:
#   logical k maps to entry (k % NUM_PARTITIONS) of this list.
# These are the NUM_PARTITIONS=$NUM_PARTITIONS farthest-apart CPU nodes, so the
# benchmark's two partitions sit as far apart as the machine allows.
# Hand-edit this line to choose a different pair.
export NUM_PARTITIONS=$NUM_PARTITIONS
export NUMA_NODE_ORDER=$part_csv

# Hardware threads available on the partition nodes ONLY (not the whole machine).
# The benchmarks split this in half across the two partitions, so it is even.
# Pass it to campaign.py as  --threads \$PARTITION_THREADS.
export PARTITION_THREADS=$part_threads

# numactl binding for the benchmarks (bind to exactly the partition nodes).
export NUMACTL_BIND="--cpunodebind=$bind_csv --membind=$bind_csv"
EOF

echo "Wrote $OUT"
echo "  physical nodes        : $num_phys"
echo "  CPU nodes (ascending) : $cpu_csv"
echo "  outside-in spread     : $spread_csv"
echo "  partitions            : $NUM_PARTITIONS"
echo "  NUMA_NODE_ORDER       : $part_csv   (logical k -> this[k % $NUM_PARTITIONS])"
echo "  NUMACTL_BIND          : --cpunodebind=$bind_csv --membind=$bind_csv"
echo "  PARTITION_THREADS     : $part_threads   (hw threads on nodes $part_csv)"
echo "  total threads         : $total_threads   (whole machine)"
